#############################################################################
# Makefile for building: ImageViewer.app/Contents/MacOS/ImageViewer
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  ImageViewer.pro
# Template: app
# Command: /Users/lqlin/Qt5.9.0/5.9/clang_64/bin/qmake -o Makefile ImageViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt5.9.0/5.9/clang_64/lib/QtQuick.framework/Headers -I../../../Qt5.9.0/5.9/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.9.0/5.9/clang_64/lib/QtQml.framework/Headers -I../../../Qt5.9.0/5.9/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt5.9.0/5.9/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang -F/Users/lqlin/Qt5.9.0/5.9/clang_64/lib
QMAKE         = /Users/lqlin/Qt5.9.0/5.9/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL_FILE = /Users/lqlin/Qt5.9.0/5.9/clang_64/bin/qmake -install qinstall file
QINSTALL_PROGRAM = /Users/lqlin/Qt5.9.0/5.9/clang_64/bin/qmake -install qinstall program
QINSTALL_DIR  = /Users/lqlin/Qt5.9.0/5.9/clang_64/bin/qmake -install qinstall directory
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ImageViewer1.0.0
DISTDIR = /Users/lqlin/Desktop/QtQuickProjects/ImageViewer/.tmp/ImageViewer1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/lqlin/Qt5.9.0/5.9/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/lqlin/Qt5.9.0/5.9/clang_64/lib -framework QtQuick -framework QtQml -framework QtNetwork -framework QtCore -framework DiskArbitration -framework IOKit -framework QtGui -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp qrc_qml.cpp
OBJECTS       = main.o \
		qrc_qml.o
DIST          = ../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/lex.prf \
		ImageViewer.pro  main.cpp
QMAKE_TARGET  = ImageViewer
DESTDIR       = 
TARGET        = ImageViewer.app/Contents/MacOS/ImageViewer

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d ImageViewer.app/Contents/MacOS/ || mkdir -p ImageViewer.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ImageViewer.pro ../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/toolchain.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qml_debug.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qmake_use.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/file_copies.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.9.0/5.9/clang_64/mkspecs/features/lex.prf \
		ImageViewer.pro \
		qml.qrc \
		../../../Qt5.9.0/5.9/clang_64/lib/QtQuick.framework/QtQuick.prl \
		../../../Qt5.9.0/5.9/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../Qt5.9.0/5.9/clang_64/lib/QtQml.framework/QtQml.prl \
		../../../Qt5.9.0/5.9/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		../../../Qt5.9.0/5.9/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile ImageViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/qdevice.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/unix.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/mac.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/macx.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/qconfig.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/toolchain.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/toolchain.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qml_debug.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qt.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/resources.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/moc.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/qmake_use.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/file_copies.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.9.0/5.9/clang_64/mkspecs/features/lex.prf:
ImageViewer.pro:
qml.qrc:
../../../Qt5.9.0/5.9/clang_64/lib/QtQuick.framework/QtQuick.prl:
../../../Qt5.9.0/5.9/clang_64/lib/QtGui.framework/QtGui.prl:
../../../Qt5.9.0/5.9/clang_64/lib/QtQml.framework/QtQml.prl:
../../../Qt5.9.0/5.9/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
../../../Qt5.9.0/5.9/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ImageViewer.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

ImageViewer.app/Contents/PkgInfo: 
	@test -d ImageViewer.app/Contents || mkdir -p ImageViewer.app/Contents
	@$(DEL_FILE) ImageViewer.app/Contents/PkgInfo
	@echo "APPL????" > ImageViewer.app/Contents/PkgInfo
ImageViewer.app/Contents/Resources/empty.lproj: 
	@test -d ImageViewer.app/Contents/Resources || mkdir -p ImageViewer.app/Contents/Resources
	@touch ImageViewer.app/Contents/Resources/empty.lproj
	
ImageViewer.app/Contents/Info.plist: 
	@test -d ImageViewer.app/Contents || mkdir -p ImageViewer.app/Contents
	@$(DEL_FILE) ImageViewer.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,lq.ImageViewer,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,ImageViewer,g" -e "s,@LIBRARY@,ImageViewer,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.9.0/5.9/clang_64/mkspecs/macx-clang/Info.plist.app >ImageViewer.app/Contents/Info.plist

all: Makefile \
		ImageViewer.app/Contents/PkgInfo \
		ImageViewer.app/Contents/Resources/empty.lproj \
		ImageViewer.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt5.9.0/5.9/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r ImageViewer.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		../../../Qt5.9.0/5.9/clang_64/bin/rcc \
		timg.jpeg \
		main.qml
	/Users/lqlin/Qt5.9.0/5.9/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt5.9.0/5.9/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../../Qt5.9.0/5.9/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean 

####### Compile

main.o: main.cpp ../../../Qt5.9.0/5.9/clang_64/lib/QtGui.framework/Headers/QGuiApplication \
		../../../Qt5.9.0/5.9/clang_64/lib/QtGui.framework/Headers/qguiapplication.h \
		../../../Qt5.9.0/5.9/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../Qt5.9.0/5.9/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/ImageViewer/bin || mkdir -p $(INSTALL_ROOT)/opt/ImageViewer/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ImageViewer/bin/ImageViewer.app
	
	-$(QINSTALL_DIR) ImageViewer.app $(INSTALL_ROOT)/opt/ImageViewer/bin/ImageViewer.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/ImageViewer/bin/ImageViewer.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/ImageViewer/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

